export const strings = {
  CITY_SEARCH: 'City search',
  CITY_SEARCH_CLEAR: 'Clear search',
  CITY_SEARCH_ERROR: 'Error searching cities, please check your connection.',
  CURRENT_LOCATION: 'Current Location',
  CURRENT_LOCATION_BUTTON: 'Get weather for current Location',
  SELECT_LOCATION: 'To get started, enable location services or search for a location.',
  CURRENT_WEATHER: 'Current weather',
  CURRENT_WEATHER_FEELS_LIKE: 'Feels like:',
  CURRENT_WEATHER_HUMIDITY: 'Humidity:',
  CURRENT_WEATHER_UV: 'UV:',
  CURRENT_WEATHER_WIND: 'Wind:',
  CURRENT_WEATHER_PRESSURE: 'Pressure:',
  CURRENT_WEATHER_ALERTS: 'View active weather alerts',
  RAIN_FORECAST: 'Rain Forecast',
  NEXT_7_DAYS: 'Next 7 days',
  NEXT_7_DAYS_TODAY: 'Today',
  HOURLY_WEATHER: 'Hourly weather',
  PRECIPITATION: 'Precipitation',
  TEMPERATURE: 'Temperature',
  ALERT_VALID_FROM: 'Valid from:',
  ALERT_PROVIDER: 'Data provided by:',
  TIME_NOW: 'now',
  RAIN_STATUS_NONE: 'No precipitation within {0} minutes',
  RAIN_STATUS_CONTINUING: 'Precipitation continues for {0} minutes',
  RAIN_STATUS_INTERMITTENT: 'Intermittent precipitation for {0} minutes',
  RAIN_STATUS_STARTING: 'Precipitation starts in {0} minutes',
  RAIN_STATUS_FINISHING: 'Precipitation ends in {0} minutes',
  MODAL_CLOSE: 'Close',
  LOADING: 'Loading',
  DATA_LOAD_ERROR:
    'There was an error loading weather for this location. Please check your connection and refresh the page.',
  WEATHER_NEWS: 'Weather News',
  WEATHER_NEWS_PROVIDER_PREFIX: 'From: ',
}
