export const strings = {
  LOCATION_SEARCH: 'Search location',
  CURRENT_LOCATION: 'Current Location',
  CURRENT_LOCATION_BUTTON: 'Use current Location',
  SELECT_LOCATION: 'Please select a location.',
  CURRENT_WEATHER_FEELS_LIKE: 'Feels like:',
  CURRENT_WEATHER_HUMIDITY: 'Humidity:',
  CURRENT_WEATHER_UV: 'UV:',
  CURRENT_WEATHER_WIND: 'Wind:',
  CURRENT_WEATHER_PRESSURE: 'Pressure:',
  NEXT_7_DAYS_TODAY: 'Today',
  ALERT_VALID_FROM: 'Valid from:',
  ALERT_PROVIDER: 'Data provided by:',
  RAIN_STATUS_NONE: 'No precipitation within {0} minutes',
  RAIN_STATUS_CONTINUING: 'Precipitation continues for {0} minutes',
  RAIN_STATUS_INTERMITTENT: 'Intermittent precipitation for {0} minutes',
  RAIN_STATUS_STARTING: 'Precipitation starts in {0} minutes',
  RAIN_STATUS_FINISHING: 'Precipitation ends in {0} minutes',
}
